version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    # Auto-assign reviewers and add labels
    reviewers:
      - "Flexicom-Industries-Pvt-Ltd"
    labels:
      - "dependencies"
      - "security"
  
  # Maintain GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    labels:
      - "dependencies"
      - "github-actions"
