-- AlterTable
ALTER TABLE "LoomReadingSheet" ADD COLUMN IF NOT EXISTS "averageEfficiency" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN IF NOT EXISTS "totalBreakdownMins" INTEGER DEFAULT 0;

-- AlterTable
ALTER TABLE "LoomReadingEntry" ADD COLUMN IF NOT EXISTS "breakdownReason" TEXT,
ADD COLUMN IF NOT EXISTS "breakdownMinutes" INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS "efficiencyPct" DOUBLE PRECISION DEFAULT 0;
