import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";
import { requireApiAuth } from "@/lib/api-auth";
import { Module } from "@/generated/prisma";
import { logEvent } from "@/lib/logging";

export const dynamic = "force-dynamic";

export const MASTER_LOOM_MAPPINGS = [
  {
    qualityCode: 'GRADE "B"',
    colorGroup: "Grey",
    colour: "MIX",
    denier: null,
    tapeWidth: 2.45,
    bobbinMarking: "AL",
    loomNumbers: [2, 3, 4],
    totalLooms: 3,
    reedSpaceCm: null,
    remarks: "Transition & Grade B recycled bobbins",
  },
  {
    qualityCode: "FERRUS/LPP/WH/450/57/S1",
    colorGroup: "White",
    colour: "YELLOW",
    denier: 850.0,
    tapeWidth: 3.00,
    bobbinMarking: "GREEN",
    loomNumbers: [],
    totalLooms: 0,
    reedSpaceCm: 57.0,
    remarks: "",
  },
  {
    qualityCode: "NOVCO/LPP/WHITE/64/S1",
    colorGroup: "White",
    colour: "WHITE",
    denier: 850.0,
    tapeWidth: 3.00,
    bobbinMarking: "YELLOW",
    loomNumbers: [],
    totalLooms: 0,
    reedSpaceCm: 64.0,
    remarks: "",
  },
  {
    qualityCode: "wOND/LPP/WH/500/67/S1",
    colorGroup: "Yellow",
    colour: "WHITE",
    denier: 900.0,
    tapeWidth: 3.00,
    bobbinMarking: "RED",
    loomNumbers: [6, 7, 8, 12, 14, 16, 20, 23, 24, 25, 29, 33, 34, 35, 39, 40, 41, 43, 45, 49, 52, 76, 77, 78, 83, 87, 88, 90],
    totalLooms: 28,
    reedSpaceCm: 67.0,
    remarks: "High volume running quality (28 looms)",
  },
  {
    qualityCode: "TOP/ALPP/WH/54/500/HC",
    colorGroup: "White",
    colour: "WHITE",
    denier: 850.0,
    tapeWidth: 3.00,
    bobbinMarking: "BLACK",
    loomNumbers: [30, 63, 86, 89],
    totalLooms: 4,
    reedSpaceCm: 54.0,
    remarks: "",
  },
  {
    qualityCode: "CMNYAD/LPP/WH/660/53/CP",
    colorGroup: "White",
    colour: "WHITE",
    denier: 850.0,
    tapeWidth: 3.00,
    bobbinMarking: "BLACK",
    loomNumbers: [17, 18, 21],
    totalLooms: 3,
    reedSpaceCm: 53.0,
    remarks: "",
  },
  {
    qualityCode: "CMN/AD/LPP/WH/680/89/CP",
    colorGroup: "Yellow",
    colour: "WHITE",
    denier: 850.0,
    tapeWidth: 3.00,
    bobbinMarking: "BLACK",
    loomNumbers: [],
    totalLooms: 0,
    reedSpaceCm: 89.0,
    remarks: "",
  },
  {
    qualityCode: "BVCL/LPP/YLO/500/67/HC",
    colorGroup: "Yellow",
    colour: "YELLOW",
    denier: 900.0,
    tapeWidth: 3.00,
    bobbinMarking: "GRN/RED",
    loomNumbers: [],
    totalLooms: 0,
    reedSpaceCm: 67.0,
    remarks: "",
  },
  {
    qualityCode: "STYM/YL/LPP/500/64/HC",
    colorGroup: "White",
    colour: "YELLOW",
    denier: 900.0,
    tapeWidth: 3.00,
    bobbinMarking: "GRN/RED",
    loomNumbers: [26, 27, 28],
    totalLooms: 3,
    reedSpaceCm: 64.0,
    remarks: "",
  },
  {
    qualityCode: "MAHA/LPP/WH+R/500/56",
    colorGroup: "White",
    colour: "WHITE",
    denier: 700.0,
    tapeWidth: 3.00,
    bobbinMarking: "RED/GRN/YL",
    loomNumbers: [82],
    totalLooms: 1,
    reedSpaceCm: 56.0,
    remarks: "",
  },
  {
    qualityCode: "MAHA/LPP/WHR/480/52",
    colorGroup: "White",
    colour: "WH+RED",
    denier: 700.0,
    tapeWidth: 3.00,
    bobbinMarking: "RED/GRN/YL",
    loomNumbers: [],
    totalLooms: 0,
    reedSpaceCm: 52.0,
    remarks: "",
  },
  {
    qualityCode: "MAHA/LPP/WH-RED/480/52",
    colorGroup: "White",
    colour: "WHITE",
    denier: 700.0,
    tapeWidth: 3.00,
    bobbinMarking: "RED/GRN/YL",
    loomNumbers: [31],
    totalLooms: 1,
    reedSpaceCm: 52.0,
    remarks: "",
  },
  {
    qualityCode: "UTCL/LPP/YL/500/S1",
    colorGroup: "White",
    colour: "YELLOW",
    denier: 900.0,
    tapeWidth: 3.00,
    bobbinMarking: "BLK/GRN",
    loomNumbers: [36, 46, 47, 48, 50, 51, 81],
    totalLooms: 7,
    reedSpaceCm: 50.0,
    remarks: "",
  },
  {
    qualityCode: "UTC/LPP/Y/550/89/CP/1",
    colorGroup: "White",
    colour: "YELLOW",
    denier: 900.0,
    tapeWidth: 3.00,
    bobbinMarking: "BLACK GREEN",
    loomNumbers: [15],
    totalLooms: 1,
    reedSpaceCm: 89.0,
    remarks: "",
  },
  {
    qualityCode: "ULTR/PP/YL/490/76/S1",
    colorGroup: "Dark Green",
    colour: "YELLOW",
    denier: 840.0,
    tapeWidth: 2.45,
    bobbinMarking: "GREEN",
    loomNumbers: [44, 55, 59, 60, 61, 62],
    totalLooms: 6,
    reedSpaceCm: 76.0,
    remarks: "",
  },
  {
    qualityCode: "BVCL/PP/YLO/75.5/490/HC",
    colorGroup: "White",
    colour: "YELLOW",
    denier: 825.0,
    tapeWidth: 2.45,
    bobbinMarking: "NO",
    loomNumbers: [73, 75, 91],
    totalLooms: 3,
    reedSpaceCm: 75.5,
    remarks: "",
  },
  {
    qualityCode: "AMB/PP/YLO/500/77/S1",
    colorGroup: "White",
    colour: "YELLOW",
    denier: 860.0,
    tapeWidth: 2.45,
    bobbinMarking: "RED/BLACK",
    loomNumbers: [],
    totalLooms: 0,
    reedSpaceCm: 77.0,
    remarks: "",
  },
  {
    qualityCode: "AMB/PP/YLO/500/76/S1",
    colorGroup: "Dark Green",
    colour: "YELLOW",
    denier: 815.0,
    tapeWidth: 2.45,
    bobbinMarking: "GREEN",
    loomNumbers: [9, 10, 19, 22, 37, 42, 57, 66, 67, 68],
    totalLooms: 10,
    reedSpaceCm: 76.0,
    remarks: "10 active looms allocated",
  },
  {
    qualityCode: "TOP/PP/YLO/500/76/HC",
    colorGroup: "Light Green",
    colour: "YELLOW",
    denier: 825.0,
    tapeWidth: 2.45,
    bobbinMarking: "RED",
    loomNumbers: [56, 58],
    totalLooms: 2,
    reedSpaceCm: 76.0,
    remarks: "",
  },
  {
    qualityCode: "AMB/PP/WH/500/76/S1",
    colorGroup: "Light Green",
    colour: "WHITE",
    denier: 860.0,
    tapeWidth: 2.45,
    bobbinMarking: "BLUE",
    loomNumbers: [11, 13, 32, 38, 53, 54, 64, 65, 69, 70, 71, 72, 74, 79, 80, 84, 85],
    totalLooms: 17,
    reedSpaceCm: 76.0,
    remarks: "17 active looms allocated",
  },
  {
    qualityCode: "AMB/PP/WH/500/74/S1",
    colorGroup: "Light Green",
    colour: "WH/RED",
    denier: 815.0,
    tapeWidth: 3.00,
    bobbinMarking: "BLUE/BLACK",
    loomNumbers: [],
    totalLooms: 0,
    reedSpaceCm: 74.0,
    remarks: "",
  },
  {
    qualityCode: "CC/PP/W+Y/480/77/S1",
    colorGroup: "Light Green",
    colour: "WH+YL",
    denier: 860.0,
    tapeWidth: 2.45,
    bobbinMarking: "BLUE",
    loomNumbers: [],
    totalLooms: 0,
    reedSpaceCm: 77.0,
    remarks: "",
  },
  {
    qualityCode: "C/PP/Y/480/77/S1",
    colorGroup: "Light Green",
    colour: "YELLOW",
    denier: 860.0,
    tapeWidth: 2.45,
    bobbinMarking: "RED+BLACK",
    loomNumbers: [],
    totalLooms: 0,
    reedSpaceCm: 77.0,
    remarks: "",
  },
  {
    qualityCode: "cCi/PP/Y/480/77/HC",
    colorGroup: "Light Green",
    colour: "YELLOW",
    denier: 860.0,
    tapeWidth: 2.45,
    bobbinMarking: "BLACK",
    loomNumbers: [],
    totalLooms: 0,
    reedSpaceCm: 77.0,
    remarks: "",
  },
  {
    qualityCode: "TOP/PP/WH/500/76/HC",
    colorGroup: "Light Blue",
    colour: "WHITE",
    denier: 830.0,
    tapeWidth: 2.45,
    bobbinMarking: "RED/BLUE",
    loomNumbers: [1, 5],
    totalLooms: 2,
    reedSpaceCm: 76.0,
    remarks: "",
  },
  {
    qualityCode: "UMABRIJ/PP/ORNG/490/72/HC",
    colorGroup: "Yellow",
    colour: "ORANGE",
    denier: 800.0,
    tapeWidth: 2.45,
    bobbinMarking: "NO",
    loomNumbers: [],
    totalLooms: 0,
    reedSpaceCm: 72.0,
    remarks: "",
  },
  {
    qualityCode: "BIS/SAMPLE/485/77/WH/PP/S1",
    colorGroup: "Dark Blue",
    colour: "WHITE",
    denier: 860.0,
    tapeWidth: 2.45,
    bobbinMarking: "SAMPLE",
    loomNumbers: [],
    totalLooms: 0,
    reedSpaceCm: 77.0,
    remarks: "BIS Certification Trial Quality",
  },
];

export async function POST(request: NextRequest) {
  const auth = await requireApiAuth({
    module: [Module.DATA_CENTRE, Module.PRODUCTION],
    action: "canCreate",
  });
  if (!auth.ok) return auth.response;

  try {
    let createdCount = 0;
    let updatedCount = 0;

    for (const item of MASTER_LOOM_MAPPINGS) {
      const existing = await db.loomMachineMapping.findUnique({
        where: { qualityCode: item.qualityCode },
      });

      if (existing) {
        await db.loomMachineMapping.update({
          where: { qualityCode: item.qualityCode },
          data: {
            colorGroup: item.colorGroup,
            colour: item.colour,
            denier: item.denier,
            tapeWidth: item.tapeWidth,
            bobbinMarking: item.bobbinMarking,
            loomNumbers: item.loomNumbers,
            totalLooms: item.totalLooms,
            reedSpaceCm: item.reedSpaceCm,
            remarks: item.remarks,
            isActive: true,
          },
        });
        updatedCount++;
      } else {
        await db.loomMachineMapping.create({
          data: {
            qualityCode: item.qualityCode,
            colorGroup: item.colorGroup,
            colour: item.colour,
            denier: item.denier,
            tapeWidth: item.tapeWidth,
            bobbinMarking: item.bobbinMarking,
            loomNumbers: item.loomNumbers,
            totalLooms: item.totalLooms,
            reedSpaceCm: item.reedSpaceCm,
            remarks: item.remarks,
            isActive: true,
          },
        });
        createdCount++;
      }
    }

    await logEvent({
      action: "SEED_LOOM_MAPPINGS",
      module: "DATA_CENTRE",
      severity: "INFO",
      payload: { createdCount, updatedCount, totalProcessed: MASTER_LOOM_MAPPINGS.length },
      meta: { description: `Synced ${MASTER_LOOM_MAPPINGS.length} Loom Machine Mappings from Loom Master Data` },
      userId: auth.user.id,
    });

    return NextResponse.json({
      success: true,
      message: `Master Loom Mappings synced successfully: ${createdCount} created, ${updatedCount} updated.`,
      count: MASTER_LOOM_MAPPINGS.length,
    });
  } catch (error: any) {
    console.error("Error syncing Loom Machine Mappings:", error);
    return NextResponse.json(
      { error: "Failed to sync Loom Machine Mappings" },
      { status: 500 }
    );
  }
}
