import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";
import { requireApiAuth } from "@/lib/api-auth";
import { Module } from "@/generated/prisma";
import { logEvent } from "@/lib/logging";

export const dynamic = "force-dynamic";

export interface MasterRecipeSeedItem {
  code: string;
  tapeType: string;
  denier: number | null;
  tapeWidth: number | null;
  strength: number | null;
  eloPercent: number | null;
  bobbinMarking: string | null;
  colour: string | null;
  spacerSize: number | null;
  requiredAsh: number | null;
  ashPercent: number | null;
  ppPercent: number | null;
  ccPercent: number | null;
  mbPercent: number | null;
  rp1Percent: number | null;
  rp2Percent: number | null;
  hdrpPercent: number | null;
  omega: number | null;
  vistamaxPercent: number | null;
  tptPercent: number | null;
  totalPercent: number | null;
  defaultQtyKg: number | null;
  colorGroup: string | null; // "Yellow" | "White" | "Light Green" | "Dark Green" | "Grey" | "Dark Blue" | "Light Blue"
  recipeGroup: string | null; // e.g. "860D PP Family", "900D LPP White"
  copiedFromCode: string | null;
  remarks: string | null;
}

export const DEFAULT_MASTER_RECIPES: MasterRecipeSeedItem[] = [
  // =========================================================================
  // 1. 🟡 YELLOW GROUP (High-Volume / Priority / Plant Key Indicators)
  // =========================================================================
  {
    code: "wOND/LPP/WH/500/67/S1",
    tapeType: "LPP",
    denier: 900.0,
    tapeWidth: 2.98,
    strength: 5.2,
    eloPercent: 0.26,
    bobbinMarking: "RED",
    colour: "WHITE",
    spacerSize: 7.15,
    requiredAsh: 4.0,
    ashPercent: 3.56,
    ppPercent: 90.0,
    ccPercent: 5.0,
    mbPercent: null,
    rp1Percent: 5.0,
    rp2Percent: null,
    hdrpPercent: null,
    omega: null,
    vistamaxPercent: null,
    tptPercent: null,
    totalPercent: 100,
    defaultQtyKg: 2500.0,
    colorGroup: "Yellow",
    recipeGroup: "900D LPP White (Wonder)",
    copiedFromCode: null,
    remarks: "Mega production line across 28 circular looms",
  },
  {
    code: "CMN/AD/LPP/WH/680/89/ce",
    tapeType: "LPP",
    denier: 850.0,
    tapeWidth: 2.98,
    strength: 4.65,
    eloPercent: 0.24,
    bobbinMarking: "Black",
    colour: "WHITE",
    spacerSize: 7.15,
    requiredAsh: null,
    ashPercent: 14.33,
    ppPercent: 66.0,
    ccPercent: 24.0,
    mbPercent: null,
    rp1Percent: 10.0,
    rp2Percent: null,
    hdrpPercent: 2.0,
    omega: null,
    vistamaxPercent: null,
    tptPercent: null,
    totalPercent: 100,
    defaultQtyKg: 2500.0,
    colorGroup: "Yellow",
    recipeGroup: "850D LPP White (Chettinad)",
    copiedFromCode: null,
    remarks: "Chettinad Cement 850D formulation",
  },
  {
    code: "BVCL/LPP/YIo/S00/67/HC",
    tapeType: "LPP",
    denier: 890.0,
    tapeWidth: 2.98,
    strength: 4.65,
    eloPercent: 0.24,
    bobbinMarking: "GRN/RED",
    colour: "YELLOW",
    spacerSize: 7.15,
    requiredAsh: null,
    ashPercent: null,
    ppPercent: 60.5,
    ccPercent: 20.0,
    mbPercent: 2.5,
    rp1Percent: 7.0,
    rp2Percent: 10.0,
    hdrpPercent: null,
    omega: null,
    vistamaxPercent: null,
    tptPercent: null,
    totalPercent: 100,
    defaultQtyKg: 2000.0,
    colorGroup: "Yellow",
    recipeGroup: "890D-900D LPP Yellow (Bhavya)",
    copiedFromCode: null,
    remarks: "Bhavya Cement LPP formulation",
  },
  {
    code: "UMABRIJ/PP/ORNG/490/72/HC",
    tapeType: "PP",
    denier: 800.0,
    tapeWidth: 2.45,
    strength: null,
    eloPercent: null,
    bobbinMarking: "NO",
    colour: "ORANGE",
    spacerSize: 6.15,
    requiredAsh: null,
    ashPercent: null,
    ppPercent: null,
    ccPercent: null,
    mbPercent: null,
    rp1Percent: null,
    rp2Percent: null,
    hdrpPercent: null,
    omega: null,
    vistamaxPercent: null,
    tptPercent: null,
    totalPercent: null,
    defaultQtyKg: 2000.0,
    colorGroup: "Yellow",
    recipeGroup: "800D PP Orange (Umabrij)",
    copiedFromCode: null,
    remarks: "Specialty Orange formulation - pending chemist input",
  },

  // =========================================================================
  // 2. ⚪ WHITE GROUP (Standard Base Production Lines & Maha Family)
  // =========================================================================
  {
    code: "FERRUS/LPP/WH/450/57/S1",
    tapeType: "LPP",
    denier: 850.0,
    tapeWidth: 2.98,
    strength: null,
    eloPercent: null,
    bobbinMarking: "GREEN",
    colour: "YELLOW",
    spacerSize: 7.15,
    requiredAsh: null,
    ashPercent: null,
    ppPercent: null,
    ccPercent: null,
    mbPercent: null,
    rp1Percent: null,
    rp2Percent: null,
    hdrpPercent: null,
    omega: null,
    vistamaxPercent: null,
    tptPercent: null,
    totalPercent: null,
    defaultQtyKg: 2000.0,
    colorGroup: "White",
    recipeGroup: "850D LPP Yellow (Ferrus)",
    copiedFromCode: null,
    remarks: "Ferrus quality - pending chemist input",
  },
  {
    code: "NOVCO/LPP/WHITE/64/S1",
    tapeType: "LPP",
    denier: 850.0,
    tapeWidth: 2.98,
    strength: 5.2,
    eloPercent: 0.26,
    bobbinMarking: "YELLOW",
    colour: "WHITE",
    spacerSize: 7.15,
    requiredAsh: 4.0,
    ashPercent: 3.74,
    ppPercent: 89.7,
    ccPercent: 5.3,
    mbPercent: null,
    rp1Percent: 5.0,
    rp2Percent: null,
    hdrpPercent: null,
    omega: null,
    vistamaxPercent: null,
    tptPercent: null,
    totalPercent: 100,
    defaultQtyKg: 7000.0,
    colorGroup: "White",
    recipeGroup: "850D LPP White (Novco)",
    copiedFromCode: null,
    remarks: "Novco / Nuvoco 850D White LPP",
  },
  {
    code: "TOP/ALPP/WH/54/500/eC",
    tapeType: "LPP",
    denier: 855.0,
    tapeWidth: 2.98,
    strength: 4.65,
    eloPercent: 0.24,
    bobbinMarking: "Black",
    colour: "WHITE",
    spacerSize: 7.15,
    requiredAsh: null,
    ashPercent: 14.33,
    ppPercent: 66.0,
    ccPercent: 24.0,
    mbPercent: null,
    rp1Percent: 10.0,
    rp2Percent: null,
    hdrpPercent: 2.0,
    omega: null,
    vistamaxPercent: null,
    tptPercent: null,
    totalPercent: 100,
    defaultQtyKg: 2500.0,
    colorGroup: "White",
    recipeGroup: "855D LPP White (Top)",
    copiedFromCode: null,
    remarks: "Top ALPP 855D formulation",
  },
  {
    code: "CMNYAD/LPP/WH/G6O/s3/cP",
    tapeType: "LPP",
    denier: 850.0,
    tapeWidth: 2.98,
    strength: 4.65,
    eloPercent: 0.24,
    bobbinMarking: "Black",
    colour: "WHITE",
    spacerSize: 7.15,
    requiredAsh: null,
    ashPercent: 14.33,
    ppPercent: 66.0,
    ccPercent: 24.0,
    mbPercent: null,
    rp1Percent: 10.0,
    rp2Percent: null,
    hdrpPercent: 2.0,
    omega: null,
    vistamaxPercent: null,
    tptPercent: null,
    totalPercent: 100,
    defaultQtyKg: 2500.0,
    colorGroup: "White",
    recipeGroup: "850D LPP White (Chettinad)",
    copiedFromCode: "CMN/AD/LPP/WH/680/89/ce",
    remarks: "Shares formulation with CMN/AD",
  },
  {
    code: "STYM/YL/LPP/500/64/HC",
    tapeType: "LPP",
    denier: 900.0,
    tapeWidth: 2.98,
    strength: null,
    eloPercent: null,
    bobbinMarking: "NO",
    colour: "YELLOW",
    spacerSize: 7.15,
    requiredAsh: null,
    ashPercent: null,
    ppPercent: null,
    ccPercent: null,
    mbPercent: null,
    rp1Percent: null,
    rp2Percent: null,
    hdrpPercent: null,
    omega: null,
    vistamaxPercent: null,
    tptPercent: null,
    totalPercent: null,
    defaultQtyKg: 2000.0,
    colorGroup: "White",
    recipeGroup: "900D LPP Yellow (Satyam)",
    copiedFromCode: null,
    remarks: "Satyam quality - pending chemist input",
  },
  {
    code: "MAHA/LPP/WH+R/500/56",
    tapeType: "LPP",
    denier: 700.0,
    tapeWidth: 2.98,
    strength: 4.8,
    eloPercent: 0.24,
    bobbinMarking: "RED/GRN/YL",
    colour: "WHITE",
    spacerSize: 7.15,
    requiredAsh: null,
    ashPercent: 6.5,
    ppPercent: 88.0,
    ccPercent: 7.0,
    mbPercent: null,
    rp1Percent: 5.0,
    rp2Percent: null,
    hdrpPercent: null,
    omega: null,
    vistamaxPercent: null,
    tptPercent: null,
    totalPercent: 100,
    defaultQtyKg: 2000.0,
    colorGroup: "White",
    recipeGroup: "700D LPP Maha Family",
    copiedFromCode: null,
    remarks: "Maha Cement 700D base formulation",
  },
  {
    code: "MAHA/LPP/WHR/480/52",
    tapeType: "LPP",
    denier: 700.0,
    tapeWidth: 2.98,
    strength: 4.8,
    eloPercent: 0.24,
    bobbinMarking: "RED/GRN/YL",
    colour: "WH+RED",
    spacerSize: 7.15,
    requiredAsh: null,
    ashPercent: 6.5,
    ppPercent: 88.0,
    ccPercent: 7.0,
    mbPercent: null,
    rp1Percent: 5.0,
    rp2Percent: null,
    hdrpPercent: null,
    omega: null,
    vistamaxPercent: null,
    tptPercent: null,
    totalPercent: 100,
    defaultQtyKg: 2000.0,
    colorGroup: "White",
    recipeGroup: "700D LPP Maha Family",
    copiedFromCode: "MAHA/LPP/WH+R/500/56",
    remarks: "Shares formulation with Maha Base (Dual color warp)",
  },
  {
    code: "MAHA/LPP/WH-RED/480/52",
    tapeType: "LPP",
    denier: 700.0,
    tapeWidth: 2.98,
    strength: 4.8,
    eloPercent: 0.24,
    bobbinMarking: "RED/GRN/YL",
    colour: "WHITE",
    spacerSize: 7.15,
    requiredAsh: null,
    ashPercent: 6.5,
    ppPercent: 88.0,
    ccPercent: 7.0,
    mbPercent: null,
    rp1Percent: 5.0,
    rp2Percent: null,
    hdrpPercent: null,
    omega: null,
    vistamaxPercent: null,
    tptPercent: null,
    totalPercent: 100,
    defaultQtyKg: 2000.0,
    colorGroup: "White",
    recipeGroup: "700D LPP Maha Family",
    copiedFromCode: "MAHA/LPP/WH+R/500/56",
    remarks: "Shares formulation with Maha Base",
  },
  {
    code: "UTCL/LPP/YJa/s0/s1",
    tapeType: "LPP",
    denier: 900.0,
    tapeWidth: 2.98,
    strength: 4.65,
    eloPercent: 0.24,
    bobbinMarking: "BLK/GRN",
    colour: "YELLOW",
    spacerSize: 7.15,
    requiredAsh: null,
    ashPercent: 5.0,
    ppPercent: 89.95,
    ccPercent: 3.75,
    mbPercent: 1.3,
    rp1Percent: 4.0,
    rp2Percent: 1.0,
    hdrpPercent: null,
    omega: null,
    vistamaxPercent: null,
    tptPercent: null,
    totalPercent: 100,
    defaultQtyKg: 2500.0,
    colorGroup: "White",
    recipeGroup: "900D LPP Yellow (UltraTech)",
    copiedFromCode: null,
    remarks: "UltraTech Cement 900D Yellow LPP formulation",
  },
  {
    code: "UTC/LPP/Y/s50/89/CP/1",
    tapeType: "LPP",
    denier: 900.0,
    tapeWidth: 2.98,
    strength: 4.65,
    eloPercent: 0.24,
    bobbinMarking: "Black GREEN",
    colour: "YELLOW",
    spacerSize: 7.15,
    requiredAsh: null,
    ashPercent: 5.0,
    ppPercent: 89.95,
    ccPercent: 3.75,
    mbPercent: 1.3,
    rp1Percent: 4.0,
    rp2Percent: 1.0,
    hdrpPercent: null,
    omega: null,
    vistamaxPercent: null,
    tptPercent: null,
    totalPercent: 100,
    defaultQtyKg: 2500.0,
    colorGroup: "White",
    recipeGroup: "900D LPP Yellow (UltraTech)",
    copiedFromCode: "UTCL/LPP/YJa/s0/s1",
    remarks: "Shares formulation with UTCL 900D Yellow LPP",
  },
  {
    code: "BVCL/PP/YLO/75.5/490/HC",
    tapeType: "PP",
    denier: 825.0,
    tapeWidth: 2.45,
    strength: 4.75,
    eloPercent: 0.22,
    bobbinMarking: "NO",
    colour: "YELLOW",
    spacerSize: 6.15,
    requiredAsh: null,
    ashPercent: 22.35,
    ppPercent: 56.5,
    ccPercent: 22.0,
    mbPercent: 2.5,
    rp1Percent: 5.0,
    rp2Percent: 13.0,
    hdrpPercent: null,
    omega: null,
    vistamaxPercent: null,
    tptPercent: 1.0,
    totalPercent: 100,
    defaultQtyKg: 2000.0,
    colorGroup: "White",
    recipeGroup: "825D-840D PP Yellow (Bhavya)",
    copiedFromCode: null,
    remarks: "Bhavya 825D/840D Yellow PP formulation",
  },
  {
    code: "AMB/PP/YLO/500/77/S1",
    tapeType: "PP",
    denier: 860.0,
    tapeWidth: 2.45,
    strength: 5.1,
    eloPercent: 0.24,
    bobbinMarking: "RED/BLACK",
    colour: "YELLOW",
    spacerSize: 6.15,
    requiredAsh: 5.5,
    ashPercent: 5.42,
    ppPercent: 84.8,
    ccPercent: 4.4,
    mbPercent: 0.8,
    rp1Percent: 8.0,
    rp2Percent: 2.0,
    hdrpPercent: null,
    omega: null,
    vistamaxPercent: null,
    tptPercent: null,
    totalPercent: 100,
    defaultQtyKg: 2500.0,
    colorGroup: "White",
    recipeGroup: "820D-860D PP Yellow (Ambuja)",
    copiedFromCode: null,
    remarks: "Ambuja Yellow 860D PP formulation",
  },

  // =========================================================================
  // 3. 🟢 LIGHT GREEN GROUP (860D PP Shared Extrusion Family)
  // =========================================================================
  {
    code: "AMB/PP/WH/500/76/S1",
    tapeType: "PP",
    denier: 860.0,
    tapeWidth: 2.45,
    strength: 5.1,
    eloPercent: 0.24,
    bobbinMarking: "BLUE",
    colour: "WHITE",
    spacerSize: 6.15,
    requiredAsh: 6.0,
    ashPercent: 5.45,
    ppPercent: 88.75,
    ccPercent: 6.25,
    mbPercent: null,
    rp1Percent: 3.0,
    rp2Percent: null,
    hdrpPercent: 2.0,
    omega: null,
    vistamaxPercent: null,
    tptPercent: null,
    totalPercent: 100,
    defaultQtyKg: 2500.0,
    colorGroup: "Light Green",
    recipeGroup: "860D PP Shared Formulation",
    copiedFromCode: null,
    remarks: "Base formulation for 860D PP Shared Cluster",
  },
  {
    code: "AMB/PP/WH/500/74/S1",
    tapeType: "PP",
    denier: 815.0,
    tapeWidth: 2.45,
    strength: 5.1,
    eloPercent: 0.24,
    bobbinMarking: "BLUE/BLACK",
    colour: "WH/RED",
    spacerSize: 6.15,
    requiredAsh: 6.0,
    ashPercent: 5.45,
    ppPercent: 88.75,
    ccPercent: 6.25,
    mbPercent: null,
    rp1Percent: 3.0,
    rp2Percent: null,
    hdrpPercent: 2.0,
    omega: null,
    vistamaxPercent: null,
    tptPercent: null,
    totalPercent: 100,
    defaultQtyKg: 2500.0,
    colorGroup: "Light Green",
    recipeGroup: "860D PP Shared Formulation",
    copiedFromCode: "AMB/PP/WH/500/76/S1",
    remarks: "Shares formulation with 860D PP Base",
  },
  {
    code: "CC/PP/W+Y/480/77/S1",
    tapeType: "PP",
    denier: 860.0,
    tapeWidth: 2.45,
    strength: 5.1,
    eloPercent: 0.24,
    bobbinMarking: "BLUE",
    colour: "WH+YL",
    spacerSize: 6.15,
    requiredAsh: 6.0,
    ashPercent: 5.45,
    ppPercent: 88.75,
    ccPercent: 6.25,
    mbPercent: null,
    rp1Percent: 3.0,
    rp2Percent: null,
    hdrpPercent: 2.0,
    omega: null,
    vistamaxPercent: null,
    tptPercent: null,
    totalPercent: 100,
    defaultQtyKg: 2500.0,
    colorGroup: "Light Green",
    recipeGroup: "860D PP Shared Formulation",
    copiedFromCode: "AMB/PP/WH/500/76/S1",
    remarks: "Shares formulation with 860D PP Base (Dual color warp)",
  },
  {
    code: "C/PP/Y/480/77/S1",
    tapeType: "PP",
    denier: 860.0,
    tapeWidth: 2.45,
    strength: 5.1,
    eloPercent: 0.24,
    bobbinMarking: "RED+BLACK",
    colour: "YELLOW",
    spacerSize: 6.15,
    requiredAsh: 6.0,
    ashPercent: 5.45,
    ppPercent: 88.75,
    ccPercent: 6.25,
    mbPercent: 0.8,
    rp1Percent: 3.0,
    rp2Percent: null,
    hdrpPercent: 2.0,
    omega: null,
    vistamaxPercent: null,
    tptPercent: null,
    totalPercent: 100,
    defaultQtyKg: 2500.0,
    colorGroup: "Light Green",
    recipeGroup: "860D PP Shared Formulation",
    copiedFromCode: "AMB/PP/WH/500/76/S1",
    remarks: "Shares formulation with 860D PP Base (Yellow variation)",
  },
  {
    code: "cCi/PP/Y/480/77/HC",
    tapeType: "PP",
    denier: 860.0,
    tapeWidth: 2.45,
    strength: 5.1,
    eloPercent: 0.24,
    bobbinMarking: "BLACK",
    colour: "YELLOW",
    spacerSize: 6.15,
    requiredAsh: 6.0,
    ashPercent: 5.45,
    ppPercent: 88.75,
    ccPercent: 6.25,
    mbPercent: 0.8,
    rp1Percent: 3.0,
    rp2Percent: null,
    hdrpPercent: 2.0,
    omega: null,
    vistamaxPercent: null,
    tptPercent: null,
    totalPercent: 100,
    defaultQtyKg: 2500.0,
    colorGroup: "Light Green",
    recipeGroup: "860D PP Shared Formulation",
    copiedFromCode: "AMB/PP/WH/500/76/S1",
    remarks: "Shares formulation with 860D PP Base (CCI Cement)",
  },
  {
    code: "TOP/PP/YLo/500/76/Hc",
    tapeType: "PP",
    denier: 825.0,
    tapeWidth: 2.45,
    strength: 4.75,
    eloPercent: 0.22,
    bobbinMarking: "RED",
    colour: "YELLOW",
    spacerSize: 6.15,
    requiredAsh: null,
    ashPercent: 20.50,
    ppPercent: 59.7,
    ccPercent: 19.0,
    mbPercent: 2.3,
    rp1Percent: 10.0,
    rp2Percent: 7.0,
    hdrpPercent: null,
    omega: null,
    vistamaxPercent: null,
    tptPercent: 2.0,
    totalPercent: 100,
    defaultQtyKg: 2500.0,
    colorGroup: "Light Green",
    recipeGroup: "840D PP Yellow (Top)",
    copiedFromCode: null,
    remarks: "Top Yellow 825D/840D PP formulation (A. M.B 1.3 + UT MB 1)",
  },

  // =========================================================================
  // 4. 🌲 DARK GREEN GROUP (Specialty Green Stripe / Cement Contract Lines)
  // =========================================================================
  {
    code: "ULTR/PP/YLJ490/76/SI",
    tapeType: "PP",
    denier: 840.0,
    tapeWidth: 2.45,
    strength: 4.75,
    eloPercent: 0.22,
    bobbinMarking: "GREEN",
    colour: "YELLOW",
    spacerSize: 6.15,
    requiredAsh: null,
    ashPercent: 5.25,
    ppPercent: 89.0,
    ccPercent: 5.0,
    mbPercent: 1.0,
    rp1Percent: 3.0,
    rp2Percent: 2.0,
    hdrpPercent: null,
    omega: null,
    vistamaxPercent: null,
    tptPercent: null,
    totalPercent: 100,
    defaultQtyKg: 2000.0,
    colorGroup: "Dark Green",
    recipeGroup: "840D PP Yellow (UltraTech)",
    copiedFromCode: null,
    remarks: "UltraTech Yellow 840D PP with Green Marking",
  },
  {
    code: "AMB/PP/YLo/500/76/51",
    tapeType: "PP",
    denier: 815.0,
    tapeWidth: 2.45,
    strength: 5.1,
    eloPercent: 0.24,
    bobbinMarking: "GREEN",
    colour: "YELLOW",
    spacerSize: 6.15,
    requiredAsh: 5.5,
    ashPercent: 5.42,
    ppPercent: 84.8,
    ccPercent: 4.4,
    mbPercent: 0.8,
    rp1Percent: 8.0,
    rp2Percent: 2.0,
    hdrpPercent: null,
    omega: null,
    vistamaxPercent: null,
    tptPercent: null,
    totalPercent: 100,
    defaultQtyKg: 2500.0,
    colorGroup: "Dark Green",
    recipeGroup: "820D PP Yellow (Ambuja)",
    copiedFromCode: null,
    remarks: "Ambuja Yellow 815D PP with Green Marking (10 Looms)",
  },

  // =========================================================================
  // 5. 🔘 GREY GROUP (Transition / Grade B / Recycled Lines)
  // =========================================================================
  {
    code: "GRADE \"B\"",
    tapeType: "PP",
    denier: null,
    tapeWidth: 2.45,
    strength: null,
    eloPercent: null,
    bobbinMarking: "AL",
    colour: "MIX",
    spacerSize: 6.15,
    requiredAsh: null,
    ashPercent: null,
    ppPercent: null,
    ccPercent: null,
    mbPercent: null,
    rp1Percent: null,
    rp2Percent: null,
    hdrpPercent: null,
    omega: null,
    vistamaxPercent: null,
    tptPercent: null,
    totalPercent: null,
    defaultQtyKg: 1500.0,
    colorGroup: "Grey",
    recipeGroup: "Grade B Recycled / Transition",
    copiedFromCode: null,
    remarks: "Transition bobbins / Grade B mix polymer on Looms #2, #3, #4",
  },

  // =========================================================================
  // 6. 🩵 LIGHT BLUE & 🔵 DARK BLUE GROUPS
  // =========================================================================
  {
    code: "TOP/PP/WH/500/76/HC",
    tapeType: "PP",
    denier: 830.0,
    tapeWidth: 2.45,
    strength: 4.75,
    eloPercent: 0.22,
    bobbinMarking: "RED/BLUE",
    colour: "WHITE",
    spacerSize: 6.15,
    requiredAsh: null,
    ashPercent: 19.10,
    ppPercent: 66.0,
    ccPercent: 22.0,
    mbPercent: null,
    rp1Percent: 10.0,
    rp2Percent: null,
    hdrpPercent: 2.0,
    omega: null,
    vistamaxPercent: null,
    tptPercent: null,
    totalPercent: 100,
    defaultQtyKg: 2000.0,
    colorGroup: "Light Blue",
    recipeGroup: "840D PP White (Top)",
    copiedFromCode: null,
    remarks: "Top White 830D PP with Red/Blue Marking",
  },
  {
    code: "BIS/SAMPLE/485/77/WH/PP/S1",
    tapeType: "PP",
    denier: 860.0,
    tapeWidth: 2.45,
    strength: 5.1,
    eloPercent: 0.24,
    bobbinMarking: "NO",
    colour: "WHITE",
    spacerSize: 6.15,
    requiredAsh: 6.0,
    ashPercent: 5.45,
    ppPercent: 88.75,
    ccPercent: 6.25,
    mbPercent: null,
    rp1Percent: 3.0,
    rp2Percent: null,
    hdrpPercent: 2.0,
    omega: null,
    vistamaxPercent: null,
    tptPercent: null,
    totalPercent: 100,
    defaultQtyKg: 1000.0,
    colorGroup: "Dark Blue",
    recipeGroup: "860D PP Shared Formulation",
    copiedFromCode: "AMB/PP/WH/500/76/S1",
    remarks: "BIS Certification sample run - shares 860D PP formulation",
  },
];

export async function POST(request: NextRequest) {
  const auth = await requireApiAuth({
    module: [Module.DATA_CENTRE, Module.PRODUCTION],
    action: "canCreate",
  });
  if (!auth.ok) return auth.response;

  try {
    let seededCount = 0;
    for (const r of DEFAULT_MASTER_RECIPES) {
      await db.tapePlantRecipe.upsert({
        where: { code: r.code },
        update: {
          tapeType: r.tapeType,
          denier: r.denier,
          tapeWidth: r.tapeWidth,
          strength: r.strength,
          eloPercent: r.eloPercent,
          bobbinMarking: r.bobbinMarking || null,
          colour: r.colour || null,
          spacerSize: r.spacerSize,
          requiredAsh: r.requiredAsh,
          ashPercent: r.ashPercent,
          ppPercent: r.ppPercent,
          ccPercent: r.ccPercent,
          mbPercent: r.mbPercent,
          rp1Percent: r.rp1Percent,
          rp2Percent: r.rp2Percent,
          hdrpPercent: r.hdrpPercent,
          omega: r.omega,
          vistamaxPercent: r.vistamaxPercent,
          tptPercent: r.tptPercent,
          totalPercent: r.totalPercent,
          defaultQtyKg: r.defaultQtyKg,
          colorGroup: r.colorGroup,
          recipeGroup: r.recipeGroup,
          copiedFromCode: r.copiedFromCode,
          remarks: r.remarks || null,
          isActive: true,
        },
        create: {
          code: r.code,
          tapeType: r.tapeType,
          denier: r.denier,
          tapeWidth: r.tapeWidth,
          strength: r.strength,
          eloPercent: r.eloPercent,
          bobbinMarking: r.bobbinMarking || null,
          colour: r.colour || null,
          spacerSize: r.spacerSize,
          requiredAsh: r.requiredAsh,
          ashPercent: r.ashPercent,
          ppPercent: r.ppPercent,
          ccPercent: r.ccPercent,
          mbPercent: r.mbPercent,
          rp1Percent: r.rp1Percent,
          rp2Percent: r.rp2Percent,
          hdrpPercent: r.hdrpPercent,
          omega: r.omega,
          vistamaxPercent: r.vistamaxPercent,
          tptPercent: r.tptPercent,
          totalPercent: r.totalPercent,
          defaultQtyKg: r.defaultQtyKg,
          colorGroup: r.colorGroup,
          recipeGroup: r.recipeGroup,
          copiedFromCode: r.copiedFromCode,
          remarks: r.remarks || null,
          isActive: true,
        },
      });
      seededCount++;
    }

    await logEvent({
      action: "SEED_RECIPES",
      module: "DATA_CENTRE",
      severity: "INFO",
      payload: { count: seededCount },
      meta: { description: `Seeded ${seededCount} Tape Plant Master Recipes from Loom Master Sheet` },
      userId: auth.user.id,
    });

    return NextResponse.json({
      success: true,
      message: `Successfully seeded ${seededCount} master recipes across all 7 color groups`,
    });
  } catch (error: any) {
    console.error("Error seeding Tape Plant Recipes:", error);
    return NextResponse.json(
      { error: "Failed to seed recipes" },
      { status: 500 }
    );
  }
}
