import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";
import { requireApiAuth } from "@/lib/api-auth";
import { Module } from "@/generated/prisma";
import { logEvent } from "@/lib/logging";

export const dynamic = "force-dynamic";

const DEFAULT_MASTER_RECIPES = [
  {
    code: "AMB/PP/YL/74/500/S1",
    tapeType: "PP",
    denier: 820.0,
    tapeWidth: 2.45,
    strength: 5.1,
    eloPercent: 0.24,
    bobbinMarking: "BLACK - GREEN",
    colour: "YELLOW",
    spacerSize: 6.15,
    requiredAsh: 5.5,
    ashPercent: 5.42,
    ppPercent: 84.8,
    ccPercent: 4.4,
    mbPercent: 0.8,
    rp1Percent: 8.0,
    rp2Percent: 2.0,
    hdrpPercent: null,
    tptPercent: null,
    totalPercent: 100,
    defaultQtyKg: 2500.0,
    remarks: "",
  },
  {
    code: "TOP/PP/YL/76/500/HC",
    tapeType: "PP",
    denier: 840.0,
    tapeWidth: 2.45,
    strength: 4.75,
    eloPercent: 0.22,
    bobbinMarking: "RED",
    colour: "YELLOW",
    spacerSize: 6.15,
    requiredAsh: null,
    ashPercent: 20.50,
    ppPercent: 59.7,
    ccPercent: 19.0,
    mbPercent: 2.3,
    rp1Percent: 10.0,
    rp2Percent: 7.0,
    hdrpPercent: null,
    tptPercent: 2.0,
    totalPercent: 100,
    defaultQtyKg: 2500.0,
    remarks: "A. M.B 1.3 + UT MB 1",
  },
  {
    code: "AMB/PP/WHT/78/500/S1",
    tapeType: "PP",
    denier: 860.0,
    tapeWidth: 2.45,
    strength: 5.1,
    eloPercent: 0.24,
    bobbinMarking: "Blue",
    colour: "WHITE",
    spacerSize: 6.15,
    requiredAsh: 6.0,
    ashPercent: 5.45,
    ppPercent: 88.75,
    ccPercent: 6.25,
    mbPercent: null,
    rp1Percent: 3.0,
    rp2Percent: null,
    hdrpPercent: 2.0,
    tptPercent: null,
    totalPercent: 100,
    defaultQtyKg: 2500.0,
    remarks: "",
  },
  {
    code: "TOP/PP/WHT/76/500/HC",
    tapeType: "PP",
    denier: 840.0,
    tapeWidth: 2.45,
    strength: 4.75,
    eloPercent: 0.22,
    bobbinMarking: "Red Blue",
    colour: "WHITE",
    spacerSize: 6.15,
    requiredAsh: null,
    ashPercent: 19.10,
    ppPercent: 66.0,
    ccPercent: 22.0,
    mbPercent: null,
    rp1Percent: 10.0,
    rp2Percent: null,
    hdrpPercent: 2.0,
    tptPercent: null,
    totalPercent: 100,
    defaultQtyKg: 2000.0,
    remarks: "",
  },
  {
    code: "UTCL/PP/YL/75.5/495/S1",
    tapeType: "PP",
    denier: 840.0,
    tapeWidth: 2.45,
    strength: 4.75,
    eloPercent: 0.22,
    bobbinMarking: "RED",
    colour: "YELLOW",
    spacerSize: 6.15,
    requiredAsh: null,
    ashPercent: 5.25,
    ppPercent: 89.0,
    ccPercent: 5.0,
    mbPercent: 1.0,
    rp1Percent: 3.0,
    rp2Percent: 2.0,
    hdrpPercent: null,
    tptPercent: null,
    totalPercent: 100,
    defaultQtyKg: 2000.0,
    remarks: "",
  },
  {
    code: "BVCL/PP/YL/75.5/495/HC",
    tapeType: "PP",
    denier: 840.0,
    tapeWidth: 2.45,
    strength: 4.75,
    eloPercent: 0.22,
    bobbinMarking: "",
    colour: "YELLOW",
    spacerSize: 6.15,
    requiredAsh: null,
    ashPercent: 22.35,
    ppPercent: 56.5,
    ccPercent: 22.0,
    mbPercent: 2.5,
    rp1Percent: 5.0,
    rp2Percent: 13.0,
    hdrpPercent: null,
    tptPercent: 1.0,
    totalPercent: 100,
    defaultQtyKg: 2000.0,
    remarks: "",
  },
  {
    code: "AMB/NVCO/LPP/WH/65/500/S1",
    tapeType: "LPP",
    denier: 850.0,
    tapeWidth: 2.98,
    strength: 5.2,
    eloPercent: 0.26,
    bobbinMarking: "YELLOW",
    colour: "WHITE",
    spacerSize: 7.15,
    requiredAsh: 4.0,
    ashPercent: 3.74,
    ppPercent: 89.7,
    ccPercent: 5.3,
    mbPercent: null,
    rp1Percent: 5.0,
    rp2Percent: null,
    hdrpPercent: null,
    tptPercent: null,
    totalPercent: 100,
    defaultQtyKg: 7000.0,
    remarks: "",
  },
  {
    code: "WOND/LPP/WHT/69/500/S1",
    tapeType: "LPP",
    denier: 900.0,
    tapeWidth: 2.98,
    strength: 5.2,
    eloPercent: 0.26,
    bobbinMarking: "RED",
    colour: "WHITE",
    spacerSize: 7.15,
    requiredAsh: 4.0,
    ashPercent: 3.56,
    ppPercent: 90.0,
    ccPercent: 5.0,
    mbPercent: null,
    rp1Percent: 5.0,
    rp2Percent: null,
    hdrpPercent: null,
    tptPercent: null,
    totalPercent: 100,
    defaultQtyKg: 2500.0,
    remarks: "",
  },
  {
    code: "TOP/LPP/WHT/63.5/505/HC",
    tapeType: "LPP",
    denier: 855.0,
    tapeWidth: 2.98,
    strength: 4.65,
    eloPercent: 0.24,
    bobbinMarking: "Black",
    colour: "WHITE",
    spacerSize: 7.15,
    requiredAsh: null,
    ashPercent: 14.33,
    ppPercent: 66.0,
    ccPercent: 24.0,
    mbPercent: null,
    rp1Percent: 10.0,
    rp2Percent: null,
    hdrpPercent: 2.0,
    tptPercent: null,
    totalPercent: 100,
    defaultQtyKg: 2500.0,
    remarks: "",
  },
  {
    code: "UTCL/LPP/YL/67/500/S1",
    tapeType: "LPP",
    denier: 900.0,
    tapeWidth: 2.98,
    strength: 4.65,
    eloPercent: 0.24,
    bobbinMarking: "BLACK+GREEN",
    colour: "YELLOW",
    spacerSize: 7.15,
    requiredAsh: null,
    ashPercent: 5.0,
    ppPercent: 89.95,
    ccPercent: 3.75,
    mbPercent: 1.3,
    rp1Percent: 4.0,
    rp2Percent: 1.0,
    hdrpPercent: null,
    tptPercent: null,
    totalPercent: 100,
    defaultQtyKg: 2500.0,
    remarks: "",
  },
  {
    code: "BVCL/LPP/YL/67/500/HC",
    tapeType: "LPP",
    denier: 890.0,
    tapeWidth: 2.98,
    strength: 4.65,
    eloPercent: 0.24,
    bobbinMarking: "RED + GREEN",
    colour: "YELLOW",
    spacerSize: 7.15,
    requiredAsh: null,
    ashPercent: null,
    ppPercent: 60.5,
    ccPercent: 20.0,
    mbPercent: 2.5,
    rp1Percent: 7.0,
    rp2Percent: 10.0,
    hdrpPercent: null,
    tptPercent: null,
    totalPercent: 100,
    defaultQtyKg: 2000.0,
    remarks: "",
  },
];

export async function POST(request: NextRequest) {
  const auth = await requireApiAuth({
    module: [Module.DATA_CENTRE, Module.PRODUCTION],
    action: "canCreate",
  });
  if (!auth.ok) return auth.response;

  try {
    let seededCount = 0;
    for (const r of DEFAULT_MASTER_RECIPES) {
      await db.tapePlantRecipe.upsert({
        where: { code: r.code },
        update: {
          tapeType: r.tapeType,
          denier: r.denier,
          tapeWidth: r.tapeWidth,
          strength: r.strength,
          eloPercent: r.eloPercent,
          bobbinMarking: r.bobbinMarking || null,
          colour: r.colour || null,
          spacerSize: r.spacerSize,
          requiredAsh: r.requiredAsh,
          ashPercent: r.ashPercent,
          ppPercent: r.ppPercent,
          ccPercent: r.ccPercent,
          mbPercent: r.mbPercent,
          rp1Percent: r.rp1Percent,
          rp2Percent: r.rp2Percent,
          hdrpPercent: r.hdrpPercent,
          tptPercent: r.tptPercent,
          totalPercent: r.totalPercent,
          defaultQtyKg: r.defaultQtyKg,
          remarks: r.remarks || null,
          isActive: true,
        },
        create: {
          code: r.code,
          tapeType: r.tapeType,
          denier: r.denier,
          tapeWidth: r.tapeWidth,
          strength: r.strength,
          eloPercent: r.eloPercent,
          bobbinMarking: r.bobbinMarking || null,
          colour: r.colour || null,
          spacerSize: r.spacerSize,
          requiredAsh: r.requiredAsh,
          ashPercent: r.ashPercent,
          ppPercent: r.ppPercent,
          ccPercent: r.ccPercent,
          mbPercent: r.mbPercent,
          rp1Percent: r.rp1Percent,
          rp2Percent: r.rp2Percent,
          hdrpPercent: r.hdrpPercent,
          tptPercent: r.tptPercent,
          totalPercent: r.totalPercent,
          defaultQtyKg: r.defaultQtyKg,
          remarks: r.remarks || null,
          isActive: true,
        },
      });
      seededCount++;
    }

    await logEvent({
      action: "SEED_RECIPES",
      module: "DATA_CENTRE",
      severity: "INFO",
      payload: { count: seededCount },
      meta: { description: `Seeded ${seededCount} Tape Plant Master Recipes from Excel catalog` },
      userId: auth.user.id,
    });

    return NextResponse.json({
      success: true,
      message: `Successfully seeded ${seededCount} master recipes`,
    });
  } catch (error: any) {
    console.error("Error seeding Tape Plant Recipes:", error);
    return NextResponse.json(
      { error: "Failed to seed recipes" },
      { status: 500 }
    );
  }
}
